(load (path #path ".." ".." ".." "lib.scm"))
(nut = (ceiling 0) '0)
(nut = (ceiling 0.0) '0.0)
(nut = (ceiling Infinity) 'Infinity)
(nut = (ceiling -Infinity) '-Infinity)
(nut = (ceiling NaN) 'NaN)
(nut = (ceiling 1) '1)
(nut = (ceiling 4) '4)
(nut = (ceiling -1) '-1)
(nut = (ceiling -4) '-4)
(nut = (ceiling 1.0) '1.0)
(nut = (ceiling 4.0) '4.0)
(nut = (ceiling -1.0) '-1.0)
(nut = (ceiling -4.0) '-4.0)
(nut = (ceiling 1/2) '1)
(nut = (ceiling 1/8) '1)
(nut = (ceiling -1/2) '0)
(nut = (ceiling -1/8) '0)
