(load "/Users/jordanrandleman/Desktop/EScheme/src/test/suite/procedures/../../lib.scm")
(nut = (ceil 0) '0)
(nut = (ceil 0.0) '0.0)
(nut = (ceil Infinity) 'Infinity)
(nut = (ceil -Infinity) '-Infinity)
(nut = (ceil NaN) 'NaN)
(nut = (ceil 1) '1)
(nut = (ceil 4) '4)
(nut = (ceil -1) '-1)
(nut = (ceil -4) '-4)
(nut = (ceil 1.0) '1.0)
(nut = (ceil 4.0) '4.0)
(nut = (ceil -1.0) '-1.0)
(nut = (ceil -4.0) '-4.0)
(nut = (ceil 1/2) '1)
(nut = (ceil 1/8) '1)
(nut = (ceil -1/2) '0)
(nut = (ceil -1/8) '0)
