(load "/Users/jordanrandleman/Desktop/EScheme/src/test/suite/procedures/../../lib.scm")
(nut = (denominator 0) '1)
(nut = (denominator 0.0) '1.0)
:nop
:nop
(nut = (denominator 1) '1)
(nut = (denominator 4) '1)
(nut = (denominator -1) '1)
(nut = (denominator -4) '1)
(nut = (denominator 1.0) '1.0)
(nut = (denominator 4.0) '1.0)
(nut = (denominator -1.0) '1.0)
(nut = (denominator -4.0) '1.0)
(nut = (denominator 1/2) '2)
(nut = (denominator 1/8) '8)
(nut = (denominator -1/2) '2)
(nut = (denominator -1/8) '8)
