(load (path #path ".." ".." ".." "lib.scm"))
(nut = (floor 0) '0)
(nut = (floor 0.0) '0.0)
(nut = (floor Infinity) 'Infinity)
(nut = (floor -Infinity) '-Infinity)
(nut = (floor NaN) 'NaN)
(nut = (floor 1) '1)
(nut = (floor 4) '4)
(nut = (floor -1) '-1)
(nut = (floor -4) '-4)
(nut = (floor 1.0) '1.0)
(nut = (floor 4.0) '4.0)
(nut = (floor -1.0) '-1.0)
(nut = (floor -4.0) '-4.0)
(nut = (floor 1/2) '0)
(nut = (floor 1/8) '0)
(nut = (floor -1/2) '-1)
(nut = (floor -1/8) '-1)
