(load (path #path ".." ".." ".." "lib.scm"))
(nut equal? (nan? 0) '#f)
(nut equal? (nan? 0.0) '#f)
(nut equal? (nan? Infinity) '#f)
(nut equal? (nan? -Infinity) '#f)
(nut equal? (nan? NaN) '#t)
(nut equal? (nan? 1) '#f)
(nut equal? (nan? 4) '#f)
(nut equal? (nan? -1) '#f)
(nut equal? (nan? -4) '#f)
(nut equal? (nan? 1.0) '#f)
(nut equal? (nan? 4.0) '#f)
(nut equal? (nan? -1.0) '#f)
(nut equal? (nan? -4.0) '#f)
(nut equal? (nan? 1/2) '#f)
(nut equal? (nan? 1/8) '#f)
(nut equal? (nan? -1/2) '#f)
(nut equal? (nan? -1/8) '#f)
