(load "/Users/jordanrandleman/Desktop/EScheme/src/test/suite/procedures/../../lib.scm")
(nut = (max 0) '0)
(nut = (max 0.0) '0.0)
(nut = (max Infinity) 'Infinity)
(nut = (max -Infinity) '-Infinity)
(nut = (max NaN) 'NaN)
(nut = (max 1) '1)
(nut = (max 4) '4)
(nut = (max -1) '-1)
(nut = (max -4) '-4)
(nut = (max 1.0) '1.0)
(nut = (max 4.0) '4.0)
(nut = (max -1.0) '-1.0)
(nut = (max -4.0) '-4.0)
(nut = (max 1/2) '1/2)
(nut = (max 1/8) '1/8)
(nut = (max -1/2) '-1/2)
(nut = (max -1/8) '-1/8)
