(load (path #path ".." ".." ".." "lib.scm"))
(nut = (truncate 0) '0)
(nut = (truncate 0.0) '0.0)
(nut = (truncate Infinity) 'Infinity)
(nut = (truncate -Infinity) '-Infinity)
(nut = (truncate NaN) 'NaN)
(nut = (truncate 1) '1)
(nut = (truncate 4) '4)
(nut = (truncate -1) '-1)
(nut = (truncate -4) '-4)
(nut = (truncate 1.0) '1.0)
(nut = (truncate 4.0) '4.0)
(nut = (truncate -1.0) '-1.0)
(nut = (truncate -4.0) '-4.0)
(nut = (truncate 1/2) '0)
(nut = (truncate 1/8) '0)
(nut = (truncate -1/2) '0)
(nut = (truncate -1/8) '0)
